# Site settings
title: "Juan Medina Resume"
description: "Juan Medina Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Juan Medina"
resume_title:                   "Technical Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jamedina@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+44 780 123 4425"
resume_contact_address:         "35 Lipscomb Lane - Shenley Church End, Milton Keynes MK5 6JQ, UK"

resume_header_contact_info:     "35 Lipscomb Lane - Shenley Church End, Milton Keynes MK5 6JQ, UK +44 780 123 4425"
display_header_contact_info:    "true"

resume_header_intro: "<p>I start my career many years ago as an indie game developer and work abroad 4 different countries since them, from embedded software to complex enterprise applications.</p>
<p>I like to have a polyglottal & learning by example approach to discover new patterns and solutions and always try to experiment with new technologies.</p>
<p>Alongside the way I've understood that more important than frameworks, tools or write clever code is to understand and support the people that you work with.</p>
<p>Nowadays I do as much mentoring and couching as I can to improve the teams that I work with."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_publications:    true
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/juan-medina"
  resume_twitter_url:           "https://twitter.com/JuanMedinaCode"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://juan-medina.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
  resume_amazon_url:            "https://www.amazon.co.uk/-/e/B0786Q3WBX"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

exclude: ["_screenshots", "CNAME", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]